library("SummarizedExperiment")
library("tidyverse")
library("DEP")
library("testthat")
library("shiny")
library("shinydashboard")
library("shinyjs")
library("shinyalert")
library("ComplexHeatmap")
library("limma")
library("DT")
library("ggrepel")
library("httr")
library("rjson")
library("svglite")
library("ensembldb")
library(EnsDb.Hsapiens.v86)
library("conflicted")
library("plotly")
conflict_prefer("box", "shinydashboard")
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
# source("R/functions.R")
# source("R/volcano_function.R")
# source("R/tests.R")
# source("R/demo_functions.R")
# source("R/enrichment_functions.R")
