library("SummarizedExperiment")
library("tidyverse")
library("DEP")
library("testthat")
library("shiny")
library("shinydashboard")
library("shinyjs")
library("shinyalert")
library("ComplexHeatmap")
library("dplyr")
library("limma")
library("DT")
library("ggrepel")
library("httr")
library("rjson")
library("svglite")
library("ensembldb")
library(EnsDb.Hsapiens.v86)
library("conflicted")
library("plotly")
library("shinyWidgets")# new added
library("ggVennDiagram") # new added
library("rhandsontable") # new added
library("shinyBS") # new added
library("shinycssloaders") # new added
library("shiny.info")
library("fastcluster")
library("factoextra")
library("UpSetR")

conflict_prefer("box", "shinydashboard")
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("desc", "dplyr")
conflict_prefer("setdiff", "base")
conflict_prefer("unite", "tidyr")
conflict_prefer("intersect", "base")
conflict_prefer("colMedians", "matrixStats")

source("R/functions.R")
source("R/volcano_function.R")
source("R/customized.R")
source("R/tests.R")
source("R/demo_functions.R")
source("R/enrichment_functions.R")
source("R/filter.R")
